build: false

environment:
    PYTHON: "C:\Python36"
    PYTHON_VERSION: "3.6.3"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "cmake_installer/1.0"
    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "lasote"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_STABLE_BRANCH_PATTERN: "master"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - py -m pip install conan --upgrade
  - py -m pip install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
